### ISSUE TITLE
installation fails on macOS

### ISSUE THREAD

**Issue by sg-s** [DmitryUlyanov/Multicore-TSNE#1]
I followed the instructions on this [link](https://github.com/RobeDM/LIBIRWLS#compiling-1) to get a version of gcc that supports openmp. 

but it looks like the install script isn't using gcc:

```
-- The C compiler identification is AppleClang 8.0.0.8000038
-- The CXX compiler identification is AppleClang 8.0.0.8000038
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
```

help?

**Comment by DmitryUlyanov** [comment]
I do not have mac, but you can try to modify cmake comand inside `setup.py` according to
http://stackoverflow.com/questions/24380456/how-can-i-make-cmake-use-gcc-instead-of-clang-on-mac-os-x

**Comment by sg-s** [comment]
thanks, i was trying to do that. i'll give your link a shot and report back

**Comment by DmitryUlyanov** [comment]
https://github.com/DmitryUlyanov/Multicore-TSNE/commit/9d9568e659ea03e9ba6250e51080c97a55f1bf4f
This should fix it, try one more time.

**Comment by sg-s** [comment]
sorry, still getting an error. 

I modified the setup script (line 15) with:

```python
os.system('mkdir -p multicore_tsne/release ; rm -r multicore_tsne/release/* ; cd multicore_tsne/release ; cmake -DCMAKE_C_COMPILER=/usr/local/bin/gcc-6 -DCMAKE_CXX_COMPILER=/usr/local/bin/gcc-6 -DCMAKE_BUILD_TYPE=RELEASE .. ; make CC=/usr/local/bin/gcc-6 VERBOSE=1')
```

and then when I run `python setup.py install`, I get this:

```
running install
rm: multicore_tsne/release/*: No such file or directory
-- The C compiler identification is GNU 6.2.0
-- The CXX compiler identification is GNU 6.2.0
-- Checking whether C compiler has -isysroot
-- Checking whether C compiler has -isysroot - yes
-- Checking whether C compiler supports OSX deployment target flag
-- Checking whether C compiler supports OSX deployment target flag - yes
-- Check for working C compiler: /usr/local/bin/gcc-6
-- Check for working C compiler: /usr/local/bin/gcc-6 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Checking whether CXX compiler has -isysroot
-- Checking whether CXX compiler has -isysroot - yes
-- Checking whether CXX compiler supports OSX deployment target flag
-- Checking whether CXX compiler supports OSX deployment target flag - yes
-- Check for working CXX compiler: /usr/local/bin/gcc-6
-- Check for working CXX compiler: /usr/local/bin/gcc-6 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- Configuring done
-- Generating done
-- Build files have been written to: /code/Multicore-TSNE/multicore_tsne/release
/usr/local/Cellar/cmake/3.6.2/bin/cmake -H/code/Multicore-TSNE/multicore_tsne -B/code/Multicore-TSNE/multicore_tsne/release --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/Cellar/cmake/3.6.2/bin/cmake -E cmake_progress_start /code/Multicore-TSNE/multicore_tsne/release/CMakeFiles /code/Multicore-TSNE/multicore_tsne/release/CMakeFiles/progress.marks
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/Makefile2 all
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/tsne_multicore.dir/build.make CMakeFiles/tsne_multicore.dir/depend
cd /code/Multicore-TSNE/multicore_tsne/release && /usr/local/Cellar/cmake/3.6.2/bin/cmake -E cmake_depends "Unix Makefiles" /code/Multicore-TSNE/multicore_tsne /code/Multicore-TSNE/multicore_tsne /code/Multicore-TSNE/multicore_tsne/release /code/Multicore-TSNE/multicore_tsne/release /code/Multicore-TSNE/multicore_tsne/release/CMakeFiles/tsne_multicore.dir/DependInfo.cmake --color=
Dependee "/code/Multicore-TSNE/multicore_tsne/release/CMakeFiles/tsne_multicore.dir/DependInfo.cmake" is newer than depender "/code/Multicore-TSNE/multicore_tsne/release/CMakeFiles/tsne_multicore.dir/depend.internal".
Dependee "/code/Multicore-TSNE/multicore_tsne/release/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/code/Multicore-TSNE/multicore_tsne/release/CMakeFiles/tsne_multicore.dir/depend.internal".
Scanning dependencies of target tsne_multicore
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/tsne_multicore.dir/build.make CMakeFiles/tsne_multicore.dir/build
[ 33%] Building CXX object CMakeFiles/tsne_multicore.dir/quadtree.cpp.o
/usr/local/bin/gcc-6   -Dtsne_multicore_EXPORTS  -fopenmp -O3 -fPIC -ffast-math -funroll-loops -O3 -DNDEBUG -fPIC   -o CMakeFiles/tsne_multicore.dir/quadtree.cpp.o -c /code/Multicore-TSNE/multicore_tsne/quadtree.cpp
In file included from /code/Multicore-TSNE/multicore_tsne/quadtree.cpp:15:0:
/code/Multicore-TSNE/multicore_tsne/quadtree.h: In function 'double abs(double)':
/code/Multicore-TSNE/multicore_tsne/quadtree.h:17:34: error: 'double abs(double)' conflicts with a previous declaration
 static inline double abs(double x) { return (x < .0 ? -x : x); }
                                  ^
In file included from /usr/local/Cellar/gcc/6.2.0/include/c++/6.2.0/math.h:36:0,
                 from /code/Multicore-TSNE/multicore_tsne/quadtree.cpp:11:
/usr/local/Cellar/gcc/6.2.0/include/c++/6.2.0/cmath:85:3: note: previous declaration 'constexpr double std::abs(double)'
   abs(double __x)
   ^~~
make[2]: *** [CMakeFiles/tsne_multicore.dir/quadtree.cpp.o] Error 1
make[1]: *** [CMakeFiles/tsne_multicore.dir/all] Error 2
make: *** [all] Error 2
cp: multicore_tsne/release/libtsne_multicore.so: No such file or directory
running build
running build_py
creating build
creating build/lib
creating build/lib/MulticoreTSNE
copying python/__init__.py -> build/lib/MulticoreTSNE
running egg_info
creating MulticoreTSNE.egg-info
writing MulticoreTSNE.egg-info/PKG-INFO
writing top-level names to MulticoreTSNE.egg-info/top_level.txt
writing requirements to MulticoreTSNE.egg-info/requires.txt
writing dependency_links to MulticoreTSNE.egg-info/dependency_links.txt
writing manifest file 'MulticoreTSNE.egg-info/SOURCES.txt'
reading manifest file 'MulticoreTSNE.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'python/libtsne_multicore.so'
writing manifest file 'MulticoreTSNE.egg-info/SOURCES.txt'
running install_lib
copying build/lib/MulticoreTSNE/__init__.py -> /Users/sigbhu/anaconda3/lib/python3.5/site-packages/MulticoreTSNE
byte-compiling /Users/sigbhu/anaconda3/lib/python3.5/site-packages/MulticoreTSNE/__init__.py to __init__.cpython-35.pyc
running install_egg_info
removing '/Users/sigbhu/anaconda3/lib/python3.5/site-packages/MulticoreTSNE-0.1-py3.5.egg-info' (and everything under it)
Copying MulticoreTSNE.egg-info to /Users/sigbhu/anaconda3/lib/python3.5/site-packages/MulticoreTSNE-0.1-py3.5.egg-info
```

**Comment by DmitryUlyanov** [comment]
Can you try to remove this line ? https://github.com/DmitryUlyanov/Multicore-TSNE/blob/9d9568e659ea03e9ba6250e51080c97a55f1bf4f/multicore_tsne/quadtree.h#L17

It looks like this function never used anyway.

**Comment by sg-s** [comment]
thanks, that removes the error I see, but I get a new one:

```
running install
rm: multicore_tsne/release/*: No such file or directory
-- The C compiler identification is GNU 6.2.0
-- The CXX compiler identification is GNU 6.2.0
-- Checking whether C compiler has -isysroot
-- Checking whether C compiler has -isysroot - yes
-- Checking whether C compiler supports OSX deployment target flag
-- Checking whether C compiler supports OSX deployment target flag - yes
-- Check for working C compiler: /usr/local/bin/gcc-6
-- Check for working C compiler: /usr/local/bin/gcc-6 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Checking whether CXX compiler has -isysroot
-- Checking whether CXX compiler has -isysroot - yes
-- Checking whether CXX compiler supports OSX deployment target flag
-- Checking whether CXX compiler supports OSX deployment target flag - yes
-- Check for working CXX compiler: /usr/local/bin/gcc-6
-- Check for working CXX compiler: /usr/local/bin/gcc-6 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- Configuring done
-- Generating done
-- Build files have been written to: /code/Multicore-TSNE/multicore_tsne/release
/usr/local/Cellar/cmake/3.6.2/bin/cmake -H/code/Multicore-TSNE/multicore_tsne -B/code/Multicore-TSNE/multicore_tsne/release --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/Cellar/cmake/3.6.2/bin/cmake -E cmake_progress_start /code/Multicore-TSNE/multicore_tsne/release/CMakeFiles /code/Multicore-TSNE/multicore_tsne/release/CMakeFiles/progress.marks
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/Makefile2 all
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/tsne_multicore.dir/build.make CMakeFiles/tsne_multicore.dir/depend
cd /code/Multicore-TSNE/multicore_tsne/release && /usr/local/Cellar/cmake/3.6.2/bin/cmake -E cmake_depends "Unix Makefiles" /code/Multicore-TSNE/multicore_tsne /code/Multicore-TSNE/multicore_tsne /code/Multicore-TSNE/multicore_tsne/release /code/Multicore-TSNE/multicore_tsne/release /code/Multicore-TSNE/multicore_tsne/release/CMakeFiles/tsne_multicore.dir/DependInfo.cmake --color=
Dependee "/code/Multicore-TSNE/multicore_tsne/release/CMakeFiles/tsne_multicore.dir/DependInfo.cmake" is newer than depender "/code/Multicore-TSNE/multicore_tsne/release/CMakeFiles/tsne_multicore.dir/depend.internal".
Dependee "/code/Multicore-TSNE/multicore_tsne/release/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/code/Multicore-TSNE/multicore_tsne/release/CMakeFiles/tsne_multicore.dir/depend.internal".
Scanning dependencies of target tsne_multicore
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/tsne_multicore.dir/build.make CMakeFiles/tsne_multicore.dir/build
[ 33%] Building CXX object CMakeFiles/tsne_multicore.dir/quadtree.cpp.o
/usr/local/bin/gcc-6   -Dtsne_multicore_EXPORTS  -fopenmp -O3 -fPIC -ffast-math -funroll-loops -O3 -DNDEBUG -fPIC   -o CMakeFiles/tsne_multicore.dir/quadtree.cpp.o -c /code/Multicore-TSNE/multicore_tsne/quadtree.cpp
[ 66%] Building CXX object CMakeFiles/tsne_multicore.dir/tsne.cpp.o
/usr/local/bin/gcc-6   -Dtsne_multicore_EXPORTS  -fopenmp -O3 -fPIC -ffast-math -funroll-loops -O3 -DNDEBUG -fPIC   -o CMakeFiles/tsne_multicore.dir/tsne.cpp.o -c /code/Multicore-TSNE/multicore_tsne/tsne.cpp
/var/folders/l0/4wm5tl_57j5fv3c_d__gksk40000gn/T//ccGUjHhj.s:2657:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/l0/4wm5tl_57j5fv3c_d__gksk40000gn/T//ccGUjHhj.s:2657:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/l0/4wm5tl_57j5fv3c_d__gksk40000gn/T//ccGUjHhj.s:16349:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/l0/4wm5tl_57j5fv3c_d__gksk40000gn/T//ccGUjHhj.s:16349:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
[100%] Linking CXX shared module libtsne_multicore.so
/usr/local/Cellar/cmake/3.6.2/bin/cmake -E cmake_link_script CMakeFiles/tsne_multicore.dir/link.txt --verbose=1
/usr/local/bin/gcc-6   -fopenmp -O3 -fPIC -ffast-math -funroll-loops -O3 -DNDEBUG -bundle -Wl,-headerpad_max_install_names  -o libtsne_multicore.so CMakeFiles/tsne_multicore.dir/quadtree.cpp.o CMakeFiles/tsne_multicore.dir/tsne.cpp.o 
Undefined symbols for architecture x86_64:
  "std::ios_base::Init::Init()", referenced from:
      __GLOBAL__sub_I_tsne.cpp in tsne.cpp.o
  "std::ios_base::Init::~Init()", referenced from:
      __GLOBAL__sub_I_tsne.cpp in tsne.cpp.o
  "std::__throw_bad_alloc()", referenced from:
      TSNE::computeGaussianPerplexity(double*, int, int, int**, int**, double**, double, int) [clone ._omp_fn.1] in tsne.cpp.o
      TSNE::computeGaussianPerplexity(double*, int, int, int**, int**, double**, double, int) in tsne.cpp.o
      std::vector<DataPoint, std::allocator<DataPoint> >::operator=(std::vector<DataPoint, std::allocator<DataPoint> > const&) in tsne.cpp.o
  "std::terminate()", referenced from:
      TSNE::computeGaussianPerplexity(double*, int, int, int**, int**, double**, double, int) [clone ._omp_fn.1] in tsne.cpp.o
  "operator delete[](void*)", referenced from:
      QuadTree::QuadTree(double*, int) in quadtree.cpp.o
  "operator delete(void*)", referenced from:
      TSNE::computeGaussianPerplexity(double*, int, int, int**, int**, double**, double, int) [clone ._omp_fn.1] in tsne.cpp.o
      TSNE::computeGaussianPerplexity(double*, int, int, int**, int**, double**, double, int) in tsne.cpp.o
      std::vector<DataPoint, std::allocator<DataPoint> >::operator=(std::vector<DataPoint, std::allocator<DataPoint> > const&) in tsne.cpp.o
      void std::vector<DataPoint, std::allocator<DataPoint> >::_M_emplace_back_aux<DataPoint const&>(DataPoint const&) in tsne.cpp.o
      void std::vector<double, std::allocator<double> >::_M_emplace_back_aux<double const&>(double const&) in tsne.cpp.o
      void std::vector<VpTree<DataPoint, &(euclidean_distance(DataPoint const&, DataPoint const&))>::HeapItem, std::allocator<VpTree<DataPoint, &(euclidean_distance(DataPoint const&, DataPoint const&))>::HeapItem> >::_M_emplace_back_aux<VpTree<DataPoint, &(euclidean_distance(DataPoint const&, DataPoint const&))>::HeapItem>(VpTree<DataPoint, &(euclidean_distance(DataPoint const&, DataPoint const&))>::HeapItem&&) in tsne.cpp.o
  "operator delete(void*, unsigned long)", referenced from:
      QuadTree::~QuadTree() in quadtree.cpp.o
      QuadTree::~QuadTree() in quadtree.cpp.o
      TSNE::computeGradient(int*, int*, double*, double*, int, int, double*, double) in tsne.cpp.o
      TSNE::evaluateError(int*, int*, double*, double*, int, double) in tsne.cpp.o
      TSNE::computeGaussianPerplexity(double*, int, int, int**, int**, double**, double, int) in tsne.cpp.o
      VpTree<DataPoint, &(euclidean_distance(DataPoint const&, DataPoint const&))>::Node::~Node() in tsne.cpp.o
  "operator new[](unsigned long)", referenced from:
      QuadTree::QuadTree(double*, int) in quadtree.cpp.o
  "operator new(unsigned long)", referenced from:
      QuadTree::subdivide()     in quadtree.cpp.o
      TSNE::computeGradient(int*, int*, double*, double*, int, int, double*, double) in tsne.cpp.o
      TSNE::evaluateError(int*, int*, double*, double*, int, double) in tsne.cpp.o
      TSNE::computeGaussianPerplexity(double*, int, int, int**, int**, double**, double, int) [clone ._omp_fn.1] in tsne.cpp.o
      TSNE::computeGaussianPerplexity(double*, int, int, int**, int**, double**, double, int) in tsne.cpp.o
      std::vector<DataPoint, std::allocator<DataPoint> >::operator=(std::vector<DataPoint, std::allocator<DataPoint> > const&) in tsne.cpp.o
      void std::vector<DataPoint, std::allocator<DataPoint> >::_M_emplace_back_aux<DataPoint const&>(DataPoint const&) in tsne.cpp.o
      ...
  "___gxx_personality_v0", referenced from:
      Dwarf Exception Unwind Info (__eh_frame) in tsne.cpp.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [libtsne_multicore.so] Error 1
make[1]: *** [CMakeFiles/tsne_multicore.dir/all] Error 2
make: *** [all] Error 2
cp: multicore_tsne/release/libtsne_multicore.so: No such file or directory
running build
running build_py
creating build
creating build/lib
creating build/lib/MulticoreTSNE
copying python/__init__.py -> build/lib/MulticoreTSNE
running egg_info
creating MulticoreTSNE.egg-info
writing dependency_links to MulticoreTSNE.egg-info/dependency_links.txt
writing MulticoreTSNE.egg-info/PKG-INFO
writing requirements to MulticoreTSNE.egg-info/requires.txt
writing top-level names to MulticoreTSNE.egg-info/top_level.txt
writing manifest file 'MulticoreTSNE.egg-info/SOURCES.txt'
reading manifest file 'MulticoreTSNE.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'python/libtsne_multicore.so'
writing manifest file 'MulticoreTSNE.egg-info/SOURCES.txt'
running install_lib
copying build/lib/MulticoreTSNE/__init__.py -> /Users/sigbhu/anaconda3/lib/python3.5/site-packages/MulticoreTSNE
byte-compiling /Users/sigbhu/anaconda3/lib/python3.5/site-packages/MulticoreTSNE/__init__.py to __init__.cpython-35.pyc
running install_egg_info
removing '/Users/sigbhu/anaconda3/lib/python3.5/site-packages/MulticoreTSNE-0.1-py3.5.egg-info' (and everything under it)
Copying MulticoreTSNE.egg-info to /Users/sigbhu/anaconda3/lib/python3.5/site-packages/MulticoreTSNE-0.1-py3.5.egg-info
```

**Comment by adelr** [comment]
You shouldn't have to change the installation script. If you specify the path to GCC in the CC environment variable before running the installation script, it should use the right compiler. 
In other words, typing the following in your terminal should do the trick:
`export CC="CC=/usr/local/bin/gcc-6"; python setup.py install `

**Comment by sg-s** [comment]
Hi @adelr, that isn't right. `cmake` doesn't listen to `CC` or `CXX` options

**Comment by adelr** [comment]
Hi @sg-s, starting from the original (non-modified) setup script, on Mac OS 10.11.6 (with anaconda python 3.5.2 or 2.7.12) I get an error similar to your original one because clang is being used by default:

```
python setup.py install
running install
-- The C compiler identification is AppleClang 8.0.0.8000038
-- The CXX compiler identification is AppleClang 8.0.0.8000038
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Try OpenMP C flag = [-fopenmp=libomp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
...
```
However, if I specify the path to gcc (I'm using gcc5.4 from macports) in CC, the installation works without a problem:

```
export CC="/opt/local/bin/gcc"; python setup.py install
running install
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Checking whether C compiler has -isysroot
-- Checking whether C compiler has -isysroot - yes
-- Checking whether C compiler supports OSX deployment target flag
-- Checking whether C compiler supports OSX deployment target flag - yes
-- Check for working C compiler: /opt/local/bin/gcc
-- Check for working C compiler: /opt/local/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Checking whether CXX compiler has -isysroot
-- Checking whether CXX compiler has -isysroot - yes
-- Checking whether CXX compiler supports OSX deployment target flag
-- Checking whether CXX compiler supports OSX deployment target flag - yes
-- Check for working CXX compiler: /opt/local/bin/c++
-- Check for working CXX compiler: /opt/local/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/adel/Programming/Python/Repos/Multicore-TSNE/multicore_tsne/release
/opt/local/bin/cmake -H/Users/adel/Programming/Python/Repos/Multicore-TSNE/multicore_tsne -B/Users/adel/Programming/Python/Repos/Multicore-TSNE/multicore_tsne/release --check-build-system CMakeFiles/Makefile.cmake 0
/opt/local/bin/cmake -E cmake_progress_start /Users/adel/Programming/Python/Repos/Multicore-TSNE/multicore_tsne/release/CMakeFiles /Users/adel/Programming/Python/Repos/Multicore-TSNE/multicore_tsne/release/CMakeFiles/progress.marks
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/Makefile2 all
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/tsne_multicore.dir/build.make CMakeFiles/tsne_multicore.dir/depend
cd /Users/adel/Programming/Python/Repos/Multicore-TSNE/multicore_tsne/release && /opt/local/bin/cmake -E cmake_depends "Unix Makefiles" /Users/adel/Programming/Python/Repos/Multicore-TSNE/multicore_tsne /Users/adel/Programming/Python/Repos/Multicore-TSNE/multicore_tsne /Users/adel/Programming/Python/Repos/Multicore-TSNE/multicore_tsne/release /Users/adel/Programming/Python/Repos/Multicore-TSNE/multicore_tsne/release /Users/adel/Programming/Python/Repos/Multicore-TSNE/multicore_tsne/release/CMakeFiles/tsne_multicore.dir/DependInfo.cmake --color=
Dependee "/Users/adel/Programming/Python/Repos/Multicore-TSNE/multicore_tsne/release/CMakeFiles/tsne_multicore.dir/DependInfo.cmake" is newer than depender "/Users/adel/Programming/Python/Repos/Multicore-TSNE/multicore_tsne/release/CMakeFiles/tsne_multicore.dir/depend.internal".
Dependee "/Users/adel/Programming/Python/Repos/Multicore-TSNE/multicore_tsne/release/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/Users/adel/Programming/Python/Repos/Multicore-TSNE/multicore_tsne/release/CMakeFiles/tsne_multicore.dir/depend.internal".
Scanning dependencies of target tsne_multicore
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/tsne_multicore.dir/build.make CMakeFiles/tsne_multicore.dir/build
[ 33%] Building CXX object CMakeFiles/tsne_multicore.dir/quadtree.cpp.o
/opt/local/bin/c++   -Dtsne_multicore_EXPORTS  -fopenmp -O3 -fPIC -ffast-math -funroll-loops -O3 -DNDEBUG -fPIC   -o CMakeFiles/tsne_multicore.dir/quadtree.cpp.o -c /Users/adel/Programming/Python/Repos/Multicore-TSNE/multicore_tsne/quadtree.cpp
[ 66%] Building CXX object CMakeFiles/tsne_multicore.dir/tsne.cpp.o
/opt/local/bin/c++   -Dtsne_multicore_EXPORTS  -fopenmp -O3 -fPIC -ffast-math -funroll-loops -O3 -DNDEBUG -fPIC   -o CMakeFiles/tsne_multicore.dir/tsne.cpp.o -c /Users/adel/Programming/Python/Repos/Multicore-TSNE/multicore_tsne/tsne.cpp
[100%] Linking CXX shared module libtsne_multicore.so
/opt/local/bin/cmake -E cmake_link_script CMakeFiles/tsne_multicore.dir/link.txt --verbose=1
/opt/local/bin/c++   -fopenmp -O3 -fPIC -ffast-math -funroll-loops -O3 -DNDEBUG -bundle -Wl,-headerpad_max_install_names  -o libtsne_multicore.so CMakeFiles/tsne_multicore.dir/quadtree.cpp.o CMakeFiles/tsne_multicore.dir/tsne.cpp.o 
[100%] Built target tsne_multicore
/opt/local/bin/cmake -E cmake_progress_start /Users/adel/Programming/Python/Repos/Multicore-TSNE/multicore_tsne/release/CMakeFiles 0
running build
running build_py
running egg_info
writing pbr to MulticoreTSNE.egg-info/pbr.json
writing top-level names to MulticoreTSNE.egg-info/top_level.txt
writing requirements to MulticoreTSNE.egg-info/requires.txt
writing MulticoreTSNE.egg-info/PKG-INFO
writing dependency_links to MulticoreTSNE.egg-info/dependency_links.txt
reading manifest file 'MulticoreTSNE.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'MulticoreTSNE.egg-info/SOURCES.txt'
copying python/libtsne_multicore.so -> build/lib/MulticoreTSNE
running install_lib
copying build/lib/MulticoreTSNE/libtsne_multicore.so -> /Users/adel/anaconda/envs/py35/lib/python3.5/site-packages/MulticoreTSNE
running install_egg_info
removing '/Users/adel/anaconda/envs/py35/lib/python3.5/site-packages/MulticoreTSNE-0.1-py3.5.egg-info' (and everything under it)
Copying MulticoreTSNE.egg-info to /Users/adel/anaconda/envs/py35/lib/python3.5/site-packages/MulticoreTSNE-0.1-py3.5.egg-info
```
Could this be a gcc6 issue?

**Comment by adelr** [comment]
This is quite odd indeed. Binary is attached. Best wishes.
[libtsne_multicore.so.gz](https://github.com/DmitryUlyanov/Multicore-TSNE/files/545246/libtsne_multicore.so.gz)

**Comment by DmitryUlyanov** [comment]
@sg-s did you try this http://stackoverflow.com/questions/11852568/gcc-4-8-on-mac-os-x-10-8-throws-undefined-symbols-for-architecture-x86-64 ?

**Comment by sg-s** [comment]
thanks @DmitryUlyanov, but that problem is when I used gcc5.4.

earlier, I had a different error, perhaps, linked to this:

https://stackoverflow.com/questions/28799074/qt-error-symbols-not-found-for-architecture-x86-64-on-mac-os-x-yosemite#28799463

**Comment by thomwolf** [comment]
I end up with the same error compiling with gcc 5.2.0 on MacOSX Sierra 10.12.1 (Undefined symbols for architecture x86_64).
I am currently investigating this but if you have any new tips on that, I am very interested !

**Comment by thomwolf** [comment]
It compile and run fine for me now on MacOSX Sierra 10.12.1
The things I did to get it to compile:
- install gcc 5.2.0 with `brew install gcc --without-multilib`
- Change line 9 of CMakeLists.txt in `SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS} -O3 -fPIC -ffast-math -funroll-loops -lstdc++")`
- compile with command `export CC="/usr/local/Cellar/gcc/5.2.0/bin/gcc-5"; export CXX="/usr/local/Cellar/gcc/5.2.0/bin/gcc-5"; python setup.py install`

Thank for this work, it is really fast indeed !

**Comment by sg-s** [comment]
wow, thanks, i'll check this out

**Comment by kylemcdonald** [comment]
thanks @thomwolf worked for me, except the current gcc version is 6.1.0, so: `export CC="/usr/local/Cellar/gcc/6.1.0/bin/gcc-6"; export CXX="/usr/local/Cellar/gcc/6.1.0/bin/gcc-6"; python setup.py install`

overall this is faster. for my task i see about 20% speedup to 8m45s running on 8 logical cores, compared to 11m for bh_tsne.

**Comment by thomwolf** [comment]
You're welcome @kylemcdonald, by the way I am a huge fan (and user) of your OF/sound work ! So thank you too (not to hijack this github issue :) )

**Comment by sg-s** [comment]
I'm going to close this, it works great for me now!

**Comment by jolespin** [comment]
I tried: 
```
CC="/usr/local/Cellar/gcc/7.1.0/bin/gcc-7"; export CXX="/usr/local/Cellar/gcc/7.1.0/bin/gcc-7"; python setup.py install
```
 I install openmp with brew and with conda but it didn't work.  Any suggestions?

**Comment by sg-s** [comment]
I wrote up some macOS specific installtion instructions [here](https://github.com/sg-s/Multicore-TSNE#installation-macos-specific)

Can you follow these and check if it works for you?

**Comment by jolespin** [comment]
Success! Thank you so much.  Very, very excited to use this. Quick question, is this implementation analagous to the original author's implementation or based on the scikit-learn version because I stumbled across this github issue: https://github.com/scikit-learn/scikit-learn/issues/8766 when I was trying to figure out if the learning rate was adaptive https://github.com/scikit-learn/scikit-learn/issues/7215

**Comment by sg-s** [comment]
@jolespin the code is identical -- i just modified the installation script and instructions to get it to work on macOS

**Comment by jolespin** [comment]
Identical to the sklearn version or the van see maaten version?

**Comment by sg-s** [comment]
identical to Dmitry's version (which is not the same as the one in scikit-learn)

**Comment by thomwolf** [comment]
It is very close to the Van der Maarten version.

**Comment by jolespin** [comment]
Awesome 🙌🏽 That is the one I have been using.  One last question, can a random seed be used with this version?  Does that warrant a separate feature request ticket?  Thanks again for your help.

**Comment by Yorko** [comment]
Solved the same issues by installing gcc-mp-4.7 with Macports and changing the corresponding line in the setup.py file to

`return_val = os.system('cmake -DCMAKE_C_COMPILER=/opt/local/bin/gcc-mp-4.7 -DCMAKE_CXX_COMPILER=/opt/local/bin/gcc-mp-4.7 -DCMAKE_BUILD_TYPE=RELEASE ..')`
